// Señales de tránsito con la imagen oficial (MUTCD, dominio público).
// Road signs with the official image. Los letreros van en inglés, como en el examen real:
// aunque presente el examen en español, las señales de la calle están en inglés.

const SIGN_IMG_EXTRA = {
  noderecha:    "MUTCD R3-1.svg",
  noizquierda:  "MUTCD R3-2.svg",
  carrilderecho:"MUTCD R3-7R.svg",
  norebasar:    "MUTCD R4-1.svg",
  nocamiones:   "MUTCD R5-2.svg",
  noestacionar: "MUTCD R7-1.svg",
  noestacionar2:"MUTCD R8-3.svg",
  vuelta:       "MUTCD W1-1R.svg",
  curvadoble:   "MUTCD W1-4R.svg",
  chevron:      "MUTCD W1-8R.svg",
  calleLateral: "MUTCD W2-2R.svg",
  cedaadelante: "MUTCD W3-2.svg",
  carriltermina:"MUTCD W4-2.svg",
  dobleSentido: "MUTCD W6-3.svg",
  tope:         "MUTCD W8-1.svg",
  resbaloso:    "MUTCD W8-5.svg",
  bicicleta:    "MUTCD W11-1.svg",
  peatones:     "MUTCD W11-2.svg",
  venado:       "MUTCD W11-3.svg",
  flechadoble:  "MUTCD W12-1.svg",
  sinsalida:    "MUTCD W14-1.svg",
  nooutlet:     "MUTCD W14-2.svg",
  obras:        "MUTCD W20-1.svg",
  abanderado:   "MUTCD W20-7 (temporary).svg",
  trabajadores: "MUTCD W21-1 (temporary).svg",
  workers:      "MUTCD W21-1a.svg"
};

const SENALES = [

  // ===== SEÑALES REGLAMENTARIAS (blancas/rojas: son la ley) =====
  {cat:"senales", sign:"noderecha",
   q:{es:"¿Qué significa esta señal?", en:"What does this sign mean?"},
   opts:[
     {es:"Prohibido dar vuelta a la derecha", en:"No right turn"},
     {es:"Debe dar vuelta a la derecha", en:"You must turn right"},
     {es:"Curva a la derecha adelante", en:"Curve to the right ahead"},
     {es:"Carril derecho cerrado", en:"Right lane closed"}],
   a:0,
   exp:{es:"El círculo rojo con la línea diagonal siempre PROHÍBE lo que muestra el símbolo. Aquí: no girar a la derecha.",
        en:"A red circle with a slash always PROHIBITS what the symbol shows. Here: no right turn."}},

  {cat:"senales", sign:"noizquierda",
   q:{es:"¿Qué significa esta señal?", en:"What does this sign mean?"},
   opts:[
     {es:"Prohibido dar vuelta a la izquierda", en:"No left turn"},
     {es:"Prohibida la vuelta en U", en:"No U-turn"},
     {es:"Debe seguir derecho", en:"You must go straight"},
     {es:"Curva a la izquierda", en:"Left curve"}],
   a:0,
   exp:{es:"No confunda esta señal con la de 'no vuelta en U': aquí la flecha dobla en ángulo, no regresa.",
        en:"Don't confuse this with 'no U-turn': here the arrow bends at an angle, it does not loop back."}},

  {cat:"senales", sign:"carrilderecho",
   q:{es:"Usted va en el carril derecho y ve esta señal. ¿Qué debe hacer?",
      en:"You are in the right lane and see this sign. What must you do?"},
   opts:[
     {es:"Dar vuelta a la derecha: es obligatorio desde ese carril", en:"Turn right: it is required from that lane"},
     {es:"Puede seguir derecho si quiere", en:"You may continue straight if you want"},
     {es:"Cambiarse al carril izquierdo", en:"Move to the left lane"},
     {es:"Detenerse antes de girar", en:"Stop before turning"}],
   a:0,
   exp:{es:"RIGHT LANE MUST TURN RIGHT obliga a girar. Si quiere seguir derecho, cámbiese de carril con tiempo.",
        en:"RIGHT LANE MUST TURN RIGHT requires you to turn. If you want to go straight, change lanes early."}},

  {cat:"senales", sign:"norebasar",
   q:{es:"¿Qué significa esta señal blanca que dice DO NOT PASS?",
      en:"What does this white DO NOT PASS sign mean?"},
   opts:[
     {es:"Prohibido rebasar en este tramo", en:"No passing along this stretch"},
     {es:"No entre a esta calle", en:"Do not enter this street"},
     {es:"No se estacione aquí", en:"No parking here"},
     {es:"El camino está cerrado", en:"The road is closed"}],
   a:0,
   exp:{es:"'Pass' aquí significa rebasar, no 'pasar'. Prohíbe adelantar a otro vehículo en ese tramo.",
        en:"'Pass' here means overtake. It prohibits passing another vehicle along that stretch."}},

  {cat:"senales", sign:"nocamiones",
   q:{es:"¿Qué indica esta señal?", en:"What does this sign indicate?"},
   opts:[
     {es:"Prohibido el paso de camiones", en:"No trucks allowed"},
     {es:"Estacionamiento para camiones", en:"Truck parking"},
     {es:"Zona de carga y descarga", en:"Loading zone"},
     {es:"Báscula para camiones adelante", en:"Truck weigh station ahead"}],
   a:0,
   exp:{es:"Los camiones no pueden usar esa vía, normalmente por peso, altura o porque es zona residencial.",
        en:"Trucks may not use that road, usually due to weight, height, or a residential area."}},

  {cat:"senales", sign:"noestacionar",
   q:{es:"Esta señal dice NO PARKING ANY TIME. ¿Qué significa?",
      en:"This sign says NO PARKING ANY TIME. What does it mean?"},
   opts:[
     {es:"No se puede estacionar a ninguna hora en la dirección de la flecha", en:"No parking at any hour in the direction of the arrow"},
     {es:"Solo se puede estacionar de noche", en:"You may only park at night"},
     {es:"Puede estacionarse 15 minutos", en:"You may park for 15 minutes"},
     {es:"Puede dejar el auto si va acompañado", en:"You may leave the car if someone stays in it"}],
   a:0,
   exp:{es:"La flecha indica hacia qué lado aplica la prohibición. 'Any time' = a ninguna hora, ningún día.",
        en:"The arrow shows which direction the restriction covers. 'Any time' means no hour, no day."}},

  {cat:"senales", sign:"noestacionar2",
   q:{es:"¿Qué significa esta señal con la letra P tachada?",
      en:"What does this sign with the crossed-out P mean?"},
   opts:[
     {es:"Prohibido estacionarse", en:"No parking"},
     {es:"Estacionamiento gratuito", en:"Free parking"},
     {es:"Estacionamiento solo para discapacitados", en:"Accessible parking only"},
     {es:"Zona de peatones", en:"Pedestrian zone"}],
   a:0,
   exp:{es:"La P significa 'parking' (estacionamiento). Tachada con rojo, lo prohíbe.",
        en:"The P stands for parking. Crossed out in red, it is prohibited."}},

  // ===== SEÑALES DE ADVERTENCIA (amarillas: peligro adelante) =====
  {cat:"senales", sign:"vuelta",
   q:{es:"¿Qué advierte esta señal amarilla?", en:"What does this yellow sign warn about?"},
   opts:[
     {es:"Una vuelta cerrada a la derecha: baje la velocidad", en:"A sharp right turn ahead: slow down"},
     {es:"Que debe girar obligatoriamente", en:"That you are required to turn"},
     {es:"Que el carril derecho termina", en:"That the right lane ends"},
     {es:"Que hay una salida a la derecha", en:"That there is an exit to the right"},],
   a:0,
   exp:{es:"La flecha en ángulo cerrado avisa de una vuelta pronunciada, más cerrada que una curva normal.",
        en:"The sharply bent arrow warns of a turn tighter than a normal curve."}},

  {cat:"senales", sign:"curvadoble",
   q:{es:"¿Qué significa esta señal?", en:"What does this sign mean?"},
   opts:[
     {es:"Curva doble: primero a la derecha y luego a la izquierda", en:"Reverse curve: first right, then left"},
     {es:"Camino en zigzag por varias millas", en:"Winding road for several miles"},
     {es:"Desviación obligatoria", en:"Mandatory detour"},
     {es:"Camino resbaloso", en:"Slippery road"}],
   a:0,
   exp:{es:"Dos curvas seguidas en sentidos opuestos. Reduzca la velocidad antes de entrar a la primera.",
        en:"Two curves in opposite directions. Slow down before entering the first one."}},

  {cat:"senales", sign:"chevron",
   q:{es:"Ve varias de estas señales seguidas en una curva. ¿Qué le indican?",
      en:"You see several of these in a row along a curve. What do they tell you?"},
   opts:[
     {es:"La dirección en que sigue la curva: manténgase dentro de su carril", en:"The direction the curve continues: stay in your lane"},
     {es:"Que debe dar vuelta ahí", en:"That you must turn there"},
     {es:"Que el camino termina", en:"That the road ends"},
     {es:"Que hay obras", en:"That there is roadwork"}],
   a:0,
   exp:{es:"Los 'chevrones' marcan el trazo de una curva pronunciada para que no se salga del camino.",
        en:"Chevrons trace a sharp curve so you don't drift off the road."}},

  {cat:"senales", sign:"calleLateral",
   q:{es:"¿Qué advierte esta señal?", en:"What does this sign warn about?"},
   opts:[
     {es:"Una calle lateral entra por la derecha", en:"A side road enters from the right"},
     {es:"El camino se divide en dos", en:"The road splits in two"},
     {es:"Hay un puente adelante", en:"There is a bridge ahead"},
     {es:"Debe dar vuelta a la derecha", en:"You must turn right"}],
   a:0,
   exp:{es:"Puede entrar tráfico desde esa calle lateral. Esté atento y listo para ceder o frenar.",
        en:"Traffic may enter from that side road. Stay alert and be ready to yield or brake."}},

  {cat:"senales", sign:"cedaadelante",
   q:{es:"¿Qué significa esta señal amarilla con un triángulo dentro?",
      en:"What does this yellow sign with a triangle inside mean?"},
   opts:[
     {es:"Hay una señal de CEDA EL PASO más adelante", en:"There is a YIELD sign ahead"},
     {es:"Ceda el paso aquí mismo", en:"Yield right here"},
     {es:"Hay un alto adelante", en:"There is a stop sign ahead"},
     {es:"Fin de la carretera", en:"End of the highway"}],
   a:0,
   exp:{es:"Es un aviso anticipado: prepárese para ceder el paso más adelante.",
        en:"It is advance warning: get ready to yield further ahead."}},

  {cat:"senales", sign:"carriltermina",
   q:{es:"¿Qué le indica esta señal?", en:"What is this sign telling you?"},
   opts:[
     {es:"El carril derecho termina: incorpórese con tiempo", en:"The right lane ends: merge early"},
     {es:"Se abre un carril nuevo", en:"A new lane is opening"},
     {es:"Puede rebasar por la derecha", en:"You may pass on the right"},
     {es:"Zona de estacionamiento", en:"Parking area"}],
   a:0,
   exp:{es:"No espere hasta el final del carril. Señalice y cámbiese en cuanto haya espacio seguro.",
        en:"Don't wait until the lane runs out. Signal and merge as soon as there's a safe gap."}},

  {cat:"senales", sign:"dobleSentido",
   q:{es:"¿Qué significa esta señal con dos flechas opuestas?",
      en:"What does this sign with two opposing arrows mean?"},
   opts:[
     {es:"Comienza el tráfico en dos sentidos: puede venir tráfico de frente", en:"Two-way traffic begins: oncoming traffic ahead"},
     {es:"Puede manejar en cualquier carril", en:"You may drive in either lane"},
     {es:"Hay un carril para rebasar", en:"There is a passing lane"},
     {es:"Fin del camino dividido para siempre", en:"The divided road ends permanently"}],
   a:0,
   exp:{es:"Aparece cuando termina una carretera dividida. A partir de ahí puede venir tráfico de frente: no rebase sin ver.",
        en:"It appears where a divided highway ends. From there oncoming traffic is possible: don't pass blindly."}},

  {cat:"senales", sign:"tope",
   q:{es:"La señal dice BUMP. ¿Qué debe hacer?",
      en:"The sign says BUMP. What should you do?"},
   opts:[
     {es:"Reducir la velocidad: hay un tope o desnivel en el pavimento", en:"Slow down: there is a bump in the pavement"},
     {es:"Acelerar para pasarlo rápido", en:"Speed up to get over it quickly"},
     {es:"Cambiarse de carril", en:"Change lanes"},
     {es:"Detenerse por completo", en:"Come to a complete stop"}],
   a:0,
   exp:{es:"'Bump' es un tope o bordo. Pasarlo rápido daña el vehículo y puede hacerle perder el control.",
        en:"A bump can damage your vehicle and cost you control if you hit it fast."}},

  {cat:"senales", sign:"resbaloso",
   q:{es:"¿Qué advierte esta señal del auto con líneas onduladas?",
      en:"What does this sign showing a car with wavy lines warn about?"},
   opts:[
     {es:"El camino se pone resbaloso cuando está mojado", en:"The road is slippery when wet"},
     {es:"Zona donde se permite derrapar", en:"An area where skidding is allowed"},
     {es:"Camino de grava suelta", en:"Loose gravel road"},
     {es:"Curva peligrosa", en:"Dangerous curve"}],
   a:0,
   exp:{es:"Baje la velocidad, aumente su distancia y evite frenar o girar bruscamente en ese tramo.",
        en:"Slow down, increase your following distance, and avoid hard braking or steering there."}},

  {cat:"senales", sign:"bicicleta",
   q:{es:"¿Qué significa esta señal amarilla con una bicicleta?",
      en:"What does this yellow sign with a bicycle mean?"},
   opts:[
     {es:"Cruce de ciclistas: esté atento y comparta el camino", en:"Bicycle crossing: stay alert and share the road"},
     {es:"Prohibido el paso de bicicletas", en:"No bicycles allowed"},
     {es:"Carril exclusivo para bicicletas", en:"Bicycles-only lane"},
     {es:"Estacionamiento de bicicletas", en:"Bicycle parking"}],
   a:0,
   exp:{es:"Amarillo = advertencia, no prohibición. Recuerde dejar al menos 3 pies al rebasar a un ciclista.",
        en:"Yellow means warning, not prohibition. Remember to leave at least 3 feet when passing a cyclist."}},

  {cat:"senales", sign:"peatones",
   q:{es:"¿Qué advierte esta señal?", en:"What does this sign warn about?"},
   opts:[
     {es:"Cruce de peatones: reduzca la velocidad y prepárese para ceder", en:"Pedestrian crossing: slow down and be ready to yield"},
     {es:"Prohibido el paso de peatones", en:"No pedestrians allowed"},
     {es:"Banqueta cerrada", en:"Sidewalk closed"},
     {es:"Zona escolar", en:"School zone"}],
   a:0,
   exp:{es:"La señal de zona escolar tiene forma de pentágono y dos niños. Esta es un cruce peatonal general.",
        en:"The school sign is a pentagon with two children. This one is a general pedestrian crossing."}},

  {cat:"senales", sign:"venado",
   q:{es:"En los caminos de Kansas ve esta señal. ¿Qué significa?",
      en:"On Kansas roads you see this sign. What does it mean?"},
   opts:[
     {es:"Cruce de venados: esté muy atento al amanecer y al anochecer", en:"Deer crossing: be extra alert at dawn and dusk"},
     {es:"Zona de caza permitida", en:"Hunting area"},
     {es:"Parque natural adelante", en:"Nature park ahead"},
     {es:"Rancho ganadero", en:"Cattle ranch"}],
   a:0,
   exp:{es:"Si ve un venado, probablemente vienen más detrás. Frene firme, sin volantear bruscamente.",
        en:"If you see one deer, more are likely behind it. Brake firmly without swerving."}},

  {cat:"senales", sign:"flechadoble",
   q:{es:"¿Qué le indica esta señal con flechas hacia ambos lados?",
      en:"What does this sign with arrows pointing both ways tell you?"},
   opts:[
     {es:"Puede pasar por cualquiera de los dos lados del obstáculo", en:"You may pass on either side of the obstruction"},
     {es:"El camino se divide en dos carreteras", en:"The road splits into two highways"},
     {es:"Hay tráfico en dos sentidos", en:"There is two-way traffic"},
     {es:"Debe dar vuelta en U", en:"You must make a U-turn"}],
   a:0,
   exp:{es:"Marca un camellón, isla o división. Puede rodearlo por la derecha o por la izquierda.",
        en:"It marks a median or island. You may go around it on either side."}},

  {cat:"senales", sign:"sinsalida",
   q:{es:"La señal dice DEAD END. ¿Qué significa?",
      en:"The sign says DEAD END. What does it mean?"},
   opts:[
     {es:"La calle no tiene salida: termina y hay que regresar", en:"The street has no exit: it ends and you must come back"},
     {es:"Peligro de muerte adelante", en:"Deadly danger ahead"},
     {es:"El camino está cerrado por obras", en:"The road is closed for construction"},
     {es:"Fin de la zona urbana", en:"End of the city limits"}],
   a:0,
   exp:{es:"'Dead end' = calle cerrada. Si entra, tendrá que dar vuelta y salir por donde entró.",
        en:"A dead end street stops. If you enter, you'll have to turn around and come back out."}},

  {cat:"senales", sign:"nooutlet",
   q:{es:"¿Qué significa la señal NO OUTLET?", en:"What does the NO OUTLET sign mean?"},
   opts:[
     {es:"Entrará a una zona de calles sin salida hacia otra calle", en:"You are entering an area with no through street"},
     {es:"No hay gasolinera adelante", en:"There is no gas station ahead"},
     {es:"Prohibido el paso", en:"No entry"},
     {es:"No hay alumbrado", en:"No street lights"}],
   a:0,
   exp:{es:"Parecida a DEAD END, pero indica un grupo de calles del que solo se sale por donde entró.",
        en:"Similar to DEAD END, but it marks a group of streets with only one way out."}},

  // ===== ZONA DE OBRAS (anaranjadas) =====
  {cat:"senales", sign:"obras",
   q:{es:"¿Qué significa esta señal anaranjada?", en:"What does this orange sign mean?"},
   opts:[
     {es:"Hay obras en el camino más adelante: reduzca la velocidad", en:"Road work ahead: slow down"},
     {es:"El camino está cerrado", en:"The road is closed"},
     {es:"Desviación obligatoria", en:"Mandatory detour"},
     {es:"Zona de descanso", en:"Rest area"}],
   a:0,
   exp:{es:"El anaranjado siempre indica zona de trabajo. Recuerde: en zonas de obras las multas se DUPLICAN.",
        en:"Orange always means a work zone. Remember: fines are DOUBLED in work zones."}},

  {cat:"senales", sign:"trabajadores",
   q:{es:"¿Qué significa esta señal anaranjada (MEN WORKING)?",
      en:"What does this orange sign (MEN WORKING) mean?"},
   opts:[
     {es:"Hay trabajadores sobre el camino: baje la velocidad y tenga mucho cuidado", en:"Workers are on the road: slow down and use extra care"},
     {es:"Hay una fábrica cerca", en:"There is a factory nearby"},
     {es:"Prohibido el paso a peatones", en:"No pedestrians"},
     {es:"Excavación profunda: camino cerrado", en:"Deep excavation: road closed"}],
   a:0,
   exp:{es:"Hay personas trabajando junto a los carriles, a veces a unos pasos de los autos. Baje la velocidad y no se distraiga.",
        en:"People are working beside the lanes, sometimes steps from traffic. Slow down and stay focused."}},

  {cat:"senales", sign:"workers",
   q:{es:"La señal anaranjada dice WORKERS. Usted debe:",
      en:"The orange sign says WORKERS. You should:"},
   opts:[
     {es:"Reducir la velocidad y estar listo para detenerse", en:"Slow down and be ready to stop"},
     {es:"Mantener su velocidad si no ve a nadie", en:"Keep your speed if you don't see anyone"},
     {es:"Tocar el claxon al pasar", en:"Honk as you pass"},
     {es:"Usar el acotamiento para pasar más rápido", en:"Use the shoulder to get past faster"}],
   a:0,
   exp:{es:"Aunque no vea a nadie en ese momento, puede haber trabajadores o maquinaria saliendo de repente.",
        en:"Even if you see no one at that moment, workers or equipment may pull out suddenly."}},

  {cat:"senales", sign:"abanderado",
   q:{es:"Esta señal anuncia a un abanderado (flagger) adelante. ¿Qué debe hacer?",
      en:"This sign announces a flagger ahead. What should you do?"},
   opts:[
     {es:"Obedecer sus indicaciones: tienen la misma autoridad que una señal de tránsito", en:"Obey their directions: they carry the same authority as a traffic sign"},
     {es:"Ignorarlo si el camino se ve libre", en:"Ignore them if the road looks clear"},
     {es:"Detenerse siempre por completo", en:"Always come to a full stop"},
     {es:"Seguir al auto de adelante sin fijarse", en:"Just follow the car ahead"}],
   a:0,
   exp:{es:"El abanderado dirige el tráfico en la zona de obras. Sus señas mandan sobre cualquier letrero.",
        en:"The flagger directs traffic in the work zone. Their signals override any posted sign."}}
];
